### ISSUE TITLE
Cannot import ntlm3

### ISSUE THREAD

**Issue by aflopes** [trustrachel/python-ntlm3#17]
Hi, whenever I try to import ntlm3, the module http_client is not being recognized but it is there.(six 1.10).
Can this be changed in the ntlm library side?

```
>>> import ntlm3 as ntlm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/ntlm3/__init__.py", line 2, in <module>
    from . import HTTPNtlmAuthHandler  # noqa
  File "/Library/Python/2.7/site-packages/ntlm3/HTTPNtlmAuthHandler.py", line 15, in <module>
    from six.moves.http_client import HTTPConnection, HTTPSConnection
ImportError: No module named http_client
>>>
>>>
>>> from six.moves import http_client
>>> http_client.HTTPConnection
<class httplib.HTTPConnection at 0x1054ff8d8>
```

**Comment by ohss117** [comment]
I've got the same issue here as well.

**Comment by sigmavirus24** [comment]
This is odd to me because using six 1.10.0 on Python 2.7

``` py
>>> from six.moves.http_client import HTTPConnection
>>> HTTPConnection
<class httplib.HTTPConnection at 0x1027538d8>
```

What version of Python exactly are you using? I'm on 2.7.9. You can show this by doing `python -V` at the command line.

Also, how did you install six and ntlm3?

I think by default, Apple's "version" of Python comes with a very old version of six. You should make sure this isn't falling back to that version.

**Comment by ohss117** [comment]
Thanks for the help.
I managed to fix this issue by upgrading to six 1.10.0. Mine was pretty old.

**Comment by sigmavirus24** [comment]
@trustrachel that might point towards introducing a lower cap on six then.

**Comment by beekerstudios** [comment]
I ended up installing python with homebrew (which I never used before, and was apprehensive about using YAPM) and then using it's version of PIP to install pyexchange, which NTLM3 is a dependency of, which installed it's own and correctly up to date version of 'six' (1.10.0). No matter what you do the version of six on OS X 10.11.4 never goes past 1.4.1. I sincerely believe this has more to do with OS X then it does this lib's import command, because you can search for this same type of issues with many other libs that have dependencies on 'six' and they all have a million suggestions, but pretty much none of them work. : \

Also just wanted to mention that @trustrachel is super awesome!
