### ISSUE TITLE
problem running in python 3.2

### ISSUE THREAD

**Issue by sboden** [trustrachel/python-ntlm3#19]
I installed requests-ntlm3 in python 3.2 (using v1.0.3 of the library, but also the master branch from github), I have requests-ntlm v0.2.0 and six 1.10.0.

I'm using 3.2 because for something else I need lxml which is not yet available as MSI installer yet for higher version. I distilled the piece of code that shows the problem. 

If I run it I get following (if you supply a valid website, userid and password of course): "expected bytes, not str"

```
import requests
from requests_ntlm import HttpNtlmAuth


small_url = "http://ent161.sharepoint.ibm.com/"
url = "http://ent161.sharepoint.ibm.com/teams/..."

username = r'EMEA\username'
password = 'password_here'

session = None


try:
   session = requests.Session()
   session.auth = HttpNtlmAuth(username,password,session)
   session.get(small_url)

except Exception as e:
   print(e)

```

What I get is following stack trace:

```
python w.py
Traceback (most recent call last):
  File "w.py", line 21, in <module>
    session.get(small_url)
  File "C:\Python32\lib\site-packages\requests-2.9.1-py3.2.egg\requests\sessions
.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python32\lib\site-packages\requests-2.9.1-py3.2.egg\requests\sessions
.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python32\lib\site-packages\requests-2.9.1-py3.2.egg\requests\sessions
.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Python32\lib\site-packages\requests-2.9.1-py3.2.egg\requests\hooks.py
", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Python32\lib\site-packages\requests_ntlm-0.2.0-py3.2.egg\requests_ntl
m\requests_ntlm.py", line 119, in response_hook
    'Authorization', r, kwargs)
  File "C:\Python32\lib\site-packages\requests_ntlm-0.2.0-py3.2.egg\requests_ntl
m\requests_ntlm.py", line 93, in retry_using_http_NTLM_auth
    ntlm_header_value[5:]
  File "C:\Python32\lib\site-packages\python_ntlm3-1.0.3_dev-py3.2.egg\ntlm3\ntl
m.py", line 184, in parse_NTLM_CHALLENGE_MESSAGE
    msg2 = base64.b64decode(msg2)
  File "C:\Python32\lib\base64.py", line 83, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str

```

**Comment by sigmavirus24** [comment]
So Python 3.2 has a number of bugs related to http.client in general and is unsupported. Given that this behaviour changed in (probably 3.3, but definitely 3.4) you might want to see if you can get the lxml project to publish MSIs for newer and supported versions of Python 3 (3.3, 3.4, or 3.5). 

3.2 isn't tested by this project and many projects have dropped all support for it. :/
